# -*- coding: utf-8 -*-
"""Ragas ex

Automatically generated by Colab.


"""

pip install --upgrade ragas langchain openai

pip install --upgrade langchain

import langchain
print(langchain.__version__)

pip show langchain

import os
os.environ["OPENAI_API_KEY"] = "YOUR-API-KEY"

from datasets import Dataset
from ragas.metrics import ContextPrecision, LLMContextRecall, Faithfulness
from ragas import evaluate

from langchain_openai import ChatOpenAI # Changed to ChatOpenAI
llm = ChatOpenAI(model_name="gpt-4-turbo-preview") #gpt-3.5-turbo

data = {
    "question": ["Who built the Eiffel Tower?"],
    "answer": ["It was built by Gustave Eiffel in 1889."],
    "contexts": [["Stautue of Liberty is in New York."]],
    "ground_truth": ["Gustave Eiffel built it in 1889."]
}

dataset = Dataset.from_dict(data)

results = evaluate(
    dataset,
    metrics=[ContextPrecision(), LLMContextRecall(), Faithfulness()],
    llm=llm
)

print(results)
